### ISSUE TITLE
Configure CI

### ISSUE THREAD

**Issue by rudolf-adamkovic** [enfluid/apple-audio-bar#23]

**Comment by rudolf-adamkovic** [comment]
Added to BuddyBuild:

https://dashboard.buddybuild.com/apps/5874c03feddb8801004d9ccd

Now we need to connect that with GitHub:

<img width="580" alt="screen shot 2017-01-10 at 12 12 26" src="https://cloud.githubusercontent.com/assets/1158274/21804220/200cf87e-d72e-11e6-8a28-19a7bf57b395.png">

**Comment by rudolf-adamkovic** [comment]
@enfluid Could you please fix this?

**Comment by rudolf-adamkovic** [comment]
CC: @andris-zalitis @nasakinmaxim @ruslankmlv

**Comment by rudolf-adamkovic** [comment]
Bump!

**Comment by enfluid** [comment]
Done!

**Comment by rudolf-adamkovic** [comment]
@enfluid Are branches configured properly? There's an open PR and GitHub doesn't show CI status and/or checks.

**Comment by nasakinmaxim** [comment]
@enfluid It looks like PRs can be merged without CI approval. This needs to be configured.

**Comment by enfluid** [comment]
Done.   I think when I did it before, BuddyBuild had not run yet, and so that option wasn't showing up in the branch configuration.

**Comment by rudolf-adamkovic** [comment]
CI indicators now show on PRs. Thanks @enfluid. Closing.
