### ISSUE TITLE
Rename "seek" to "skip"

### ISSUE THREAD

**Issue by nasakinmaxim** [enfluid/apple-audio-bar#47]
Skip means we're skipping a particular amount of time (forward or backward) in current media item. It is also equal to Control Center command names.

**Comment by nasakinmaxim** [comment]
Hmm. 🤔
We have `seek` method in `AVPlayer` and `skip` commands in `MPRemoteCommandCenter`. That's confusing.

@salutis @andris-zalitis @ruslankmlv 
What do you think? Should we do it?

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim 

> That's confusing.

No.

The `MPRemoteCommandCenter` has both _skip_ and _seek_:

> `var seekBackwardCommand: MPRemoteCommand`
> The command object for seeking backward through a single media item.
> 
> `var seekForwardCommand: MPRemoteCommand`
> The command object for seeking forward through a single media item.
> 
> `var skipBackwardCommand: MPSkipIntervalCommand`
> The command object for playing a previous point in a media item.
> 
> `var skipForwardCommand: MPSkipIntervalCommand`
> The command object for playing a future point in a media item.

The two mean different thing. In our case, we do "seek" not "skip".

Closing. Reopen if this doesn't answer your question.

**Comment by nasakinmaxim** [comment]
>In our case, we do "seek" not "skip".

Do we? Look at how Apple named buttons for their Podcast app. It's skip, not seek.
http://help.apple.com/iphone/10/#/iph02f70a98e

**Comment by rudolf-adamkovic** [comment]
@nasakinmaxim 

> Look at how Apple named buttons for their Podcast app.

The question was about `AVPlayer` and `MPRemoteCommandCenter`. The API is consistent.

As for how they call it in the _iPhone User Guide_, that's a discussion for another day. 😄
