### ISSUE TITLE
Update TEA to 0.15+

### ISSUE THREAD

**Issue by rudolf-adamkovic** [enfluid/apple-audio-bar#65]

**Comment by rudolf-adamkovic** [comment]
Waiting for TEA 0.15 to be released.

**Comment by rudolf-adamkovic** [comment]
Waiting for https://github.com/salutis/swift-elm-architecture/pull/151.

**Comment by rudolf-adamkovic** [comment]
Now irrelevant. See #74.

**Comment by rudolf-adamkovic** [comment]
Closed #74, reopening this one.

**Comment by nasakinmaxim** [comment]
@salutis What's the current status?

**Comment by rudolf-adamkovic** [comment]
Released Stateful 0.34 just now. Going to update this.

**Comment by rudolf-adamkovic** [comment]
Continues in #77.
